FROM debian:jessie
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y \
    wget \
    nylas

#RUN wget https://edgehill.nylas.com/download?platform=linux-deb > N1.deb
#RUN wget https://edgehill.nylas.com/download?platform=linux-deb > N1.deb
#RUN dpkg -i N1.deb
# Can't find the Electron executable at /usr/bin/electron/electron. Be sure you have run script/bootstrap first from /usr/bin or set the ELECTRON_PATH environment variable.

# /usr/share/nylas/nylas
