#!/bin/bash

del_stopped slack

docker run -it -d \
    -v /etc/localtime:/etc/localtime:ro \
   -v /tmp/.X11-unix:/tmp/.X11-unix \
   -v $HOME/.config/Slack:/root/.config/Slack \
   -e DISPLAY=unix$DISPLAY \
   --device /dev/snd:/dev/snd \
   --device /dev/dri:/dev/dri \
   --name slack \
   soulshake/slack "$@"

