#!/bin/bash

docker run -ti \
    -v $HOME/.config/keybase:/home/keybase/.config/keybase \
    -v $HOME/.cache/keybase:/home/keybase/.cache/keybase \
    -v $HOME/.gnupg:/home/keybase/.gnupg \
    soulshake/keybase "$@"
